lint:
	go vet ./...

# For superlint to work, we need:
# go install honnef.co/go/tools/cmd/staticcheck@latest
# go install golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow@latest
# go install github.com/kisielk/errcheck@latest
# go install github.com/gordonklaus/ineffassign@latest
# go install github.com/remyoudompheng/go-misc/deadcode@latest
#
superlint:
	-go vet ./...
	-go vet -vettool=/Users/mike/go/bin/shadow ./...
	-staticcheck ./...
	-errcheck -exclude .errcheck-exclude ./...
	-ineffassign ./...
	-deadcode

test:
	go test ./...

